version: '3.8'

services:
  tileserver-gl:
    image: maptiler/tileserver-gl
    container_name: tileserver-gl
    network_mode: host
    ports:
      - "8080:80"
    volumes:
      - ./data:/data
      - ./styles:/styles
      - ./config:/config
    entrypoint: ["/bin/bash", "/config/entrypoint.sh"]
    command: ["/config/poland_config.json"]
    stdin_open: true
    tty: true
    restart: unless-stopped
