name: Build & Push Docker Images

on:
  push:
    tags: ['*']
  workflow_dispatch:
    inputs:
      dockerfile:
        description: 'Dockerfile location (default: ./Dockerfile)'
        required: false
        default: './Dockerfile'
      platforms:
        description: 'Platforms to build (default: linux/amd64,linux/arm64)'
        required: false
        default: 'linux/amd64,linux/arm64'
      use_matrix:
        description: 'Build matrix for multi-arch? true/false (default: false)'
        required: false
        default: 'false'

jobs:
  build-and-push:
    uses: MapCoreGroup/.github/.github/workflows/build_and_push.yml@main
    with:
      dockerfile: ${{ inputs.dockerfile || './Dockerfile' }}
      platforms: ${{ inputs.platforms || 'linux/amd64,linux/arm64' }}
      use_matrix: ${{ inputs.use_matrix || 'false' }}
